Persist position in helpers and code tabs
qawolf/qawolf pull request #1221
Opened 2021-04-14 03:57 UTC by flaurida

* resolves #1220

2021-04-14 04:01 UTC, flaurida commented on app/components/Editor/Sidebar/HelpersEditor.tsx
> +  }, [editor, helpersLine, team]);
I don't want to re-run the hook every time this changes, safe to ignore `helpersLine` as a dependency?

2021-04-14 04:03 UTC, flaurida commented on app/components/Editor/Sidebar/CodeEditor/index.tsx
> +    if (codeLine) {
likewise not sure `codeLine` should be a dependency of `useEffect`

2021-04-14 04:15 UTC, flaurida commented on app/components/Editor/Sidebar/CodeEditor/index.tsx
> +    if (codeLine) {
(if it is it keeps setting the editor value)

2021-04-16 22:48 UTC, jperl requested changes
Going to submit a different PR with a simpler approach, just don't remove the elements from the dom when switching tabs

2021-04-16 23:03 UTC, closed without merging